version: '${version}' # Do not change!

token: "discord-bot-token"
guild-id: 123123

database:
  type: "MONGO"
  uri: "database URI"

redis:
  host: "127.0.0.1"
  port: 6368
  password: "password"
  channel: "slave:updates"

categories:
  tickets: 123123

channels:
  ticket-logs: 123123

roles:
  developer: 1231123
  support: 123123